### ISSUE TITLE
EditNodeExternal.groovy 

### ISSUE THREAD

**Issue by bepolymathe** [viaa/FreeplaneScripts#2]
Hi, 

I’am searching your script EditNodeExternal.groovy --» [https://sourceforge.net/p/freeplane/discussion/758437/thread/6f2710cf/?limit=25](https://sourceforge.net/p/freeplane/discussion/758437/thread/6f2710cf/?limit=25)
It’s still available ?

**Comment by EdoFro** [comment]
you can take a look to the forks of this project. I think there is a copy
of what you are looking for

**Comment by bepolymathe** [comment]
Yes indeed. Thanks.
